DROP TRIGGER IF EXISTS update_time_refresh ON registers CASCADE;
DROP FUNCTION IF EXISTS update_time_refresh() CASCADE;
DROP TABLE IF EXISTS registers CASCADE;
DROP TABLE IF EXISTS members CASCADE;
DROP TABLE IF EXISTS playlists CASCADE;
